const placeholderImage = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iIzMzMyIvPjx0ZXh0IHg9IjUwJSIgeT0iNTAlIiBkb21pbmFudC1iYXNlbGluZT0ibWlkZGxlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIyNHB4IiBmaWxsPSIjYWFhIj5JbWFnZSBQbGFjZWhvbGRlcjwvdGV4dD48L3N2Zz4=';

export const logo = placeholderImage;
export const bp40 = placeholderImage;
export const bp40_ch = placeholderImage;
export const stenvoy = placeholderImage;
export const sten_1 = placeholderImage;
export const sten_2 = placeholderImage;
export const sten_3 = placeholderImage;
export const razdelitel = placeholderImage;
export const razdelitel_ch = placeholderImage;
export const universal = placeholderImage;
export const universal_ch = placeholderImage;
export const potoloch = placeholderImage;
export const potoloch_ch = placeholderImage;
export const z = placeholderImage;
export const z_ch = placeholderImage;
export const b2 = placeholderImage;
export const pk14_ch = placeholderImage;
export const cornices = placeholderImage;
export const pk15 = placeholderImage;
export const pk15_ch = placeholderImage;
export const pk12 = placeholderImage;
export const pk12_ch = placeholderImage;
export const am1 = placeholderImage;
export const furnitures = placeholderImage;
export const light_lines = placeholderImage;
export const ceilingSlide = placeholderImage;